server {
    listen 4000;
    server_name _;

    root /usr/share/nginx/html;
    index edgex-status.html;

    location / {
        try_files $uri /edgex-status.html;
    }

    location /core-data/ {
        proxy_pass http://edgex-core-data:59880/;
    }

    location /core-metadata/ {
        proxy_pass http://edgex-core-metadata:59881/;
    }

    location /kuiper/ {
        proxy_pass http://edgex-kuiper:59720/;
    }
}
